- name: Set default password
  command: echo mysql-server mysql-server/root_password password my-pwd-1Z3 | sudo debconf-set-selections

- name: Set default password
  command: echo mysql-server mysql-server/root_password_again password my-pwd-1Z3 | sudo debconf-set-selections

- name: Install nginx
  apt: pkg=mysql-server libmysqlclient-dev state=latest

